<?php
$params=json_decode(file_get_contents('php://input'),true);

$date = $params['date'];
$machine = $params['machine'];
// $date = getdate(strtotime($params['date']));
// $date = getdate(strtotime($params['date']));

$data = [
    ["id" => "1",  "type" => "PostpressItem", "orderNum" => "01",  "customer" =>"Детотрюн", "duration" =>1, "machine" => "horizon1",   "options" =>"Матовая пленка", "status" => "", "dateLock" => false, "previousOrder" => null, "nextOrder" => null, "previousPart" => null, "nextPart" => null, "date" => "Sat Dec 11 2021"],
    ["id" => "2",  "type" => "PostpressItem", "orderNum" => "02",  "customer" =>"Детотрюн", "duration" =>2, "machine" => "horizon1",   "options" =>"Матовая пленка", "status" => "", "dateLock" => false, "previousOrder" => null, "nextOrder" => null, "previousPart" => null, "nextPart" => null, "date" => "Tue Dec 07 2021"],
    ["id" => "3",  "type" => "PostpressItem", "orderNum" => "03",  "customer" =>"Детотрюн", "duration" =>3, "machine" => "horizon1",   "options" =>"Матовая пленка", "status" => "", "dateLock" => false, "previousOrder" => null, "nextOrder" => null, "previousPart" => null, "nextPart" => null, "date" => "Wed Dec 08 2021"],
    ["id" => "4",  "type" => "PostpressItem", "orderNum" => "04",  "customer" =>"Детотрюн", "duration" =>6, "machine" => "horizon1",   "options" =>"Матовая пленка", "status" => "", "dateLock" => false, "previousOrder" => null, "nextOrder" => null, "previousPart" => null, "nextPart" => null, "date" => "Mon Dec 06 2021"],
    ["id" => "5",  "type" => "PostpressItem", "orderNum" => "05",  "customer" =>"Детотрюн", "duration" =>1, "machine" => "horizon1",   "options" =>"Матовая пленка", "status" => "", "dateLock" => false, "previousOrder" => null, "nextOrder" => null, "previousPart" => null, "nextPart" => null, "date" => "Mon Dec 06 2021"],
    ["id" => "6",  "type" => "PostpressItem", "orderNum" => "06",  "customer" =>"Детотрюн", "duration" =>4, "machine" => "horizon1",   "options" =>"Матовая пленка", "status" => "", "dateLock" => false, "previousOrder" => null, "nextOrder" => null, "previousPart" => null, "nextPart" => null, "date" => "Mon Dec 06 2021"],
    ["id" => "7",  "type" => "PostpressItem", "orderNum" => "07",  "customer" =>"Детотрюн", "duration" =>7, "machine" => "horizon1",   "options" =>"Матовая пленка", "status" => "", "dateLock" => false, "previousOrder" => null, "nextOrder" => null, "previousPart" => null, "nextPart" => null, "date" => "Mon Dec 06 2021"],
    ["id" => "8",  "type" => "PostpressItem", "orderNum" => "08",  "customer" =>"Детотрюн", "duration" =>2, "machine" => "horizon1",   "options" =>"Матовая пленка", "status" => "", "dateLock" => false, "previousOrder" => null, "nextOrder" => null, "previousPart" => null, "nextPart" => null, "date" => "Mon Dec 06 2021"],
    ["id" => "9",  "type" => "PostpressItem", "orderNum" => "09",  "customer" =>"Детотрюн", "duration" =>1, "machine" => "horizon2",   "options" =>"Матовая пленка", "status" => "", "dateLock" => false, "previousOrder" => null, "nextOrder" => null, "previousPart" => null, "nextPart" => null, "date" => "Fri Dec 10 2021"],
    ["id" => "10", "type" => "PostpressItem", "orderNum" => "10",  "customer" =>"Детотрюн", "duration" =>4, "machine" => "horizon2",   "options" =>"Матовая пленка", "status" => "", "dateLock" => false, "previousOrder" => null, "nextOrder" => null, "previousPart" => null, "nextPart" => null, "date" => "Fri Dec 10 2021"],
    ["id" => "11", "type" => "PostpressItem", "orderNum" => "11",  "customer" =>"Детотрюн", "duration" =>3, "machine" => "horizon2",   "options" =>"Матовая пленка", "status" => "", "dateLock" => false, "previousOrder" => null, "nextOrder" => null, "previousPart" => null, "nextPart" => null, "date" => "Fri Dec 10 2021"],
    ["id" => "12", "type" => "PostpressItem", "orderNum" => "12",  "customer" =>"Детотрюн", "duration" =>2, "machine" => "horizon2",   "options" =>"Матовая пленка", "status" => "", "dateLock" => false, "previousOrder" => null, "nextOrder" => null, "previousPart" => null, "nextPart" => null, "date" => "Wed Dec 08 2021"],
    ["id" => "13", "type" => "PostpressItem", "orderNum" => "13",  "customer" =>"Детотрюн", "duration" =>1, "machine" => "horizon2",   "options" =>"Матовая пленка", "status" => "", "dateLock" => false, "previousOrder" => null, "nextOrder" => null, "previousPart" => null, "nextPart" => null, "date" => "Tue Dec 07 2021"],
    ["id" => "14", "type" => "PostpressItem", "orderNum" => "14",  "customer" =>"Детотрюн", "duration" =>2, "machine" => "binder",     "options" =>"Матовая пленка", "status" => "", "dateLock" => false, "previousOrder" => null, "nextOrder" => null, "previousPart" => null, "nextPart" => null, "date" => "Tue Dec 07 2021"],
    ["id" => "15", "type" => "PostpressItem", "orderNum" => "15",  "customer" =>"Детотрюн", "duration" =>3, "machine" => "binder",     "options" =>"Матовая пленка", "status" => "", "dateLock" => false, "previousOrder" => null, "nextOrder" => null, "previousPart" => null, "nextPart" => null, "date" => "Wed Dec 08 2021"],
    ["id" => "16", "type" => "PostpressItem", "orderNum" => "16",  "customer" =>"Детотрюн", "duration" =>6, "machine" => "binder",     "options" =>"Матовая пленка", "status" => "", "dateLock" => false, "previousOrder" => null, "nextOrder" => null, "previousPart" => null, "nextPart" => null, "date" => "Wed Dec 08 2021"],
    ["id" => "17", "type" => "PostpressItem", "orderNum" => "17",  "customer" =>"Детотрюн", "duration" =>1, "machine" => "binder",     "options" =>"Матовая пленка", "status" => "", "dateLock" => false, "previousOrder" => null, "nextOrder" => null, "previousPart" => null, "nextPart" => null, "date" => "Sat Dec 11 2021"],
    ["id" => "18", "type" => "PostpressItem", "orderNum" => "18",  "customer" =>"Детотрюн", "duration" =>4, "machine" => "binder",     "options" =>"Матовая пленка", "status" => "", "dateLock" => false, "previousOrder" => null, "nextOrder" => null, "previousPart" => null, "nextPart" => null, "date" => "Sun Dec 12 2021"],
    ["id" => "19", "type" => "PostpressItem", "orderNum" => "19",  "customer" =>"Детотрюн", "duration" =>7, "machine" => "binder",     "options" =>"Матовая пленка", "status" => "", "dateLock" => false, "previousOrder" => null, "nextOrder" => null, "previousPart" => null, "nextPart" => null, "date" => "Sun Dec 12 2021"],
    ["id" => "20", "type" => "PostpressItem", "orderNum" => "20",  "customer" =>"Детотрюн", "duration" =>2, "machine" => "assembling", "options" =>"Матовая пленка", "status" => "", "dateLock" => false, "previousOrder" => null, "nextOrder" => null, "previousPart" => null, "nextPart" => null, "date" => "Sun Dec 12 2021"],
    ["id" => "21", "type" => "PostpressItem", "orderNum" => "21",  "customer" =>"Детотрюн", "duration" =>1, "machine" => "assembling", "options" =>"Матовая пленка", "status" => "", "dateLock" => false, "previousOrder" => null, "nextOrder" => null, "previousPart" => null, "nextPart" => null, "date" => "Thu Dec 09 2021"],
    ["id" => "22", "type" => "PostpressItem", "orderNum" => "22",  "customer" =>"Детотрюн", "duration" =>4, "machine" => "assembling", "options" =>"Матовая пленка", "status" => "", "dateLock" => false, "previousOrder" => null, "nextOrder" => null, "previousPart" => null, "nextPart" => null, "date" => "Thu Dec 09 2021"],
    ["id" => "23", "type" => "PostpressItem", "orderNum" => "23",  "customer" =>"Детотрюн", "duration" =>3, "machine" => "assembling", "options" =>"Матовая пленка", "status" => "", "dateLock" => false, "previousOrder" => null, "nextOrder" => null, "previousPart" => null, "nextPart" => null, "date" => "Thu Dec 09 2021"],
    ["id" => "24", "type" => "PostpressItem", "orderNum" => "24",  "customer" =>"Детотрюн", "duration" =>2, "machine" => "assembling", "options" =>"Матовая пленка", "status" => "", "dateLock" => false, "previousOrder" => null, "nextOrder" => null, "previousPart" => null, "nextPart" => null, "date" => "Thu Dec 09 2021"],
    ["id" => "25", "type" => "PostpressItem", "orderNum" => "101", "customer" =>"Детотрюн", "duration" =>1, "machine" => "horizon1",   "options" =>"Матовая пленка", "status" => "", "dateLock" => false, "previousOrder" => null, "nextOrder" => null, "previousPart" => null, "nextPart" => null, "date" => ""],
    ["id" => "26", "type" => "PostpressItem", "orderNum" => "102", "customer" =>"Детотрюн", "duration" =>2, "machine" => "horizon1",   "options" =>"Матовая пленка", "status" => "", "dateLock" => false, "previousOrder" => null, "nextOrder" => null, "previousPart" => null, "nextPart" => null, "date" => ""],
    ["id" => "27", "type" => "PostpressItem", "orderNum" => "103", "customer" =>"Детотрюн", "duration" =>3, "machine" => "horizon1",   "options" =>"Матовая пленка", "status" => "", "dateLock" => false, "previousOrder" => null, "nextOrder" => null, "previousPart" => null, "nextPart" => null, "date" => ""],
    ["id" => "28", "type" => "PostpressItem", "orderNum" => "104", "customer" =>"Детотрюн", "duration" =>6, "machine" => "horizon1",   "options" =>"Матовая пленка", "status" => "", "dateLock" => false, "previousOrder" => null, "nextOrder" => null, "previousPart" => null, "nextPart" => null, "date" => ""],
    ["id" => "29", "type" => "PostpressItem", "orderNum" => "105", "customer" =>"Детотрюн", "duration" =>1, "machine" => "horizon1",   "options" =>"Матовая пленка", "status" => "", "dateLock" => false, "previousOrder" => null, "nextOrder" => null, "previousPart" => null, "nextPart" => null, "date" => ""],
    ["id" => "30", "type" => "PostpressItem", "orderNum" => "106", "customer" =>"Детотрюн", "duration" =>4, "machine" => "horizon1",   "options" =>"Матовая пленка", "status" => "", "dateLock" => false, "previousOrder" => null, "nextOrder" => null, "previousPart" => null, "nextPart" => null, "date" => ""],
    ["id" => "31", "type" => "PostpressItem", "orderNum" => "107", "customer" =>"Детотрюн", "duration" =>7, "machine" => "horizon1",   "options" =>"Матовая пленка", "status" => "", "dateLock" => false, "previousOrder" => null, "nextOrder" => null, "previousPart" => null, "nextPart" => null, "date" => ""],
    ["id" => "32", "type" => "PostpressItem", "orderNum" => "108", "customer" =>"Детотрюн", "duration" =>2, "machine" => "horizon1",   "options" =>"Матовая пленка", "status" => "", "dateLock" => false, "previousOrder" => null, "nextOrder" => null, "previousPart" => null, "nextPart" => null, "date" => ""],
    ["id" => "33", "type" => "PostpressItem", "orderNum" => "109", "customer" =>"Детотрюн", "duration" =>1, "machine" => "horizon2",   "options" =>"Матовая пленка", "status" => "", "dateLock" => false, "previousOrder" => null, "nextOrder" => null, "previousPart" => null, "nextPart" => null, "date" => ""],
    ["id" => "34", "type" => "PostpressItem", "orderNum" => "110", "customer" =>"Детотрюн", "duration" =>4, "machine" => "horizon2",   "options" =>"Матовая пленка", "status" => "", "dateLock" => false, "previousOrder" => null, "nextOrder" => null, "previousPart" => null, "nextPart" => null, "date" => ""],
    ["id" => "35", "type" => "PostpressItem", "orderNum" => "111", "customer" =>"Детотрюн", "duration" =>3, "machine" => "horizon2",   "options" =>"Матовая пленка", "status" => "", "dateLock" => false, "previousOrder" => null, "nextOrder" => null, "previousPart" => null, "nextPart" => null, "date" => ""],
    ["id" => "36", "type" => "PostpressItem", "orderNum" => "112", "customer" =>"Детотрюн", "duration" =>2, "machine" => "horizon2",   "options" =>"Матовая пленка", "status" => "", "dateLock" => false, "previousOrder" => null, "nextOrder" => null, "previousPart" => null, "nextPart" => null, "date" => ""],
    ["id" => "37", "type" => "PostpressItem", "orderNum" => "113", "customer" =>"Детотрюн", "duration" =>1, "machine" => "horizon2",   "options" =>"Матовая пленка", "status" => "", "dateLock" => false, "previousOrder" => null, "nextOrder" => null, "previousPart" => null, "nextPart" => null, "date" => ""],
    ["id" => "38", "type" => "PostpressItem", "orderNum" => "114", "customer" =>"Детотрюн", "duration" =>2, "machine" => "binder",     "options" =>"Матовая пленка", "status" => "", "dateLock" => false, "previousOrder" => null, "nextOrder" => null, "previousPart" => null, "nextPart" => null, "date" => ""],
    ["id" => "39", "type" => "PostpressItem", "orderNum" => "115", "customer" =>"Детотрюн", "duration" =>3, "machine" => "binder",     "options" =>"Матовая пленка", "status" => "", "dateLock" => false, "previousOrder" => null, "nextOrder" => null, "previousPart" => null, "nextPart" => null, "date" => ""],
    ["id" => "40", "type" => "PostpressItem", "orderNum" => "116", "customer" =>"Детотрюн", "duration" =>6, "machine" => "binder",     "options" =>"Матовая пленка", "status" => "", "dateLock" => false, "previousOrder" => null, "nextOrder" => null, "previousPart" => null, "nextPart" => null, "date" => ""],
    ["id" => "41", "type" => "PostpressItem", "orderNum" => "117", "customer" =>"Детотрюн", "duration" =>1, "machine" => "binder",     "options" =>"Матовая пленка", "status" => "", "dateLock" => false, "previousOrder" => null, "nextOrder" => null, "previousPart" => null, "nextPart" => null, "date" => ""],
    ["id" => "42", "type" => "PostpressItem", "orderNum" => "118", "customer" =>"Детотрюн", "duration" =>4, "machine" => "binder",     "options" =>"Матовая пленка", "status" => "", "dateLock" => false, "previousOrder" => null, "nextOrder" => null, "previousPart" => null, "nextPart" => null, "date" => ""],
    ["id" => "43", "type" => "PostpressItem", "orderNum" => "119", "customer" =>"Детотрюн", "duration" =>7, "machine" => "binder",     "options" =>"Матовая пленка", "status" => "", "dateLock" => false, "previousOrder" => null, "nextOrder" => null, "previousPart" => null, "nextPart" => null, "date" => ""],
    ["id" => "44", "type" => "PostpressItem", "orderNum" => "120", "customer" =>"Детотрюн", "duration" =>2, "machine" => "assembling", "options" =>"Матовая пленка", "status" => "", "dateLock" => false, "previousOrder" => null, "nextOrder" => null, "previousPart" => null, "nextPart" => null, "date" => ""],
    ["id" => "45", "type" => "PostpressItem", "orderNum" => "121", "customer" =>"Детотрюн", "duration" =>1, "machine" => "assembling", "options" =>"Матовая пленка", "status" => "", "dateLock" => false, "previousOrder" => null, "nextOrder" => null, "previousPart" => null, "nextPart" => null, "date" => ""],
    ["id" => "46", "type" => "PostpressItem", "orderNum" => "122", "customer" =>"Детотрюн", "duration" =>4, "machine" => "assembling", "options" =>"Матовая пленка", "status" => "", "dateLock" => false, "previousOrder" => null, "nextOrder" => null, "previousPart" => null, "nextPart" => null, "date" => ""],
    ["id" => "47", "type" => "PostpressItem", "orderNum" => "123", "customer" =>"Детотрюн", "duration" =>3, "machine" => "assembling", "options" =>"Матовая пленка", "status" => "", "dateLock" => false, "previousOrder" => null, "nextOrder" => null, "previousPart" => null, "nextPart" => null, "date" => ""],
    ["id" => "48", "type" => "PostpressItem", "orderNum" => "124", "customer" =>"Детотрюн", "duration" =>2, "machine" => "assembling", "options" =>"Матовая пленка", "status" => "", "dateLock" => false, "previousOrder" => null, "nextOrder" => null, "previousPart" => null, "nextPart" => null, "date" => ""],
];

$output_data['notplanned'] = array_values(array_filter($data, function($item) {
    global $machine;
    return (($item['date'] == '') && ($item['machine']==$machine));
}));

$output_data['planned'] = array_values(array_filter($data, function($item) {
    global $date;
    global $machine;
    return (($item['date'] == $date) && ($item['machine']==$machine));
}));

echo json_encode($output_data);
?>